#ifndef MAPPING_H_INCLUDED
#define MAPPING_H_INCLUDED
//port A
#define GPIO0_PORT PORTA
#define GPIO1_PORT PORTA
#define GPIO2_PORT PORTA
#define GPIO3_PORT PORTA
#define GPIO4_PORT PORTA
#define GPIO5_PORT PORTA
#define GPIO6_PORT PORTA
#define GPIO7_PORT PORTA
//port B
#define GPIO8_PORT PORTB
#define GPIO9_PORT PORTB
#define GPIO10_PORT PORTB
#define GPIO11_PORT PORTB
#define GPIO12_PORT PORTB
#define GPIO13_PORT PORTB
//bit
#define GPIO0BIT	PORT0
#define GPIO1BIT	PORT1
#define GPIO2BIT	PORT2
#define GPIO3BIT	PORT3
#define GPIO4BIT	PORT4
#define GPIO5BIT	PORT5
#define GPIO6BIT	PORT6
#define GPIO7BIT	PORT7

#endif // MAPPING_H_INCLUDED
